# Generated by Django 4.0.1 on 2022-02-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_data_email_alter_data_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='created_at',
            field=models.FloatField(default=1644316328.629464),
        ),
    ]
