# Generated by Django 4.0.2 on 2022-02-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_data_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='data',
            name='created_at',
            field=models.FloatField(default=1645688158.025634),
        ),
        migrations.AlterField(
            model_name='data',
            name='phone_number',
            field=models.CharField(max_length=200, unique=True, verbose_name='شماره تماس'),
        ),
    ]
