# Generated by Django 4.0.2 on 2022-02-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_data_options_alter_data_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='created_at',
            field=models.FloatField(default=1645688960.815877),
        ),
    ]
