# Generated by Django 4.0.2 on 2022-02-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_data_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='created_at',
            field=models.FloatField(default=1645689256.33044),
        ),
    ]
